language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - hhvm
matrix:
    include:
     - php: 7.0
       env: SKIP_MEMCACHE=1
     - php: 7.1
       env: SKIP_MEMCACHE=1
    allow_failures:
     - php: 7.0
       env:
     - php: 7.1
       env:

addons:
    code_climate:
        repo_token:
            secure: "F0tPpoTZPMJkyQsElb2UKekfAcvE4P7/kAfW6/9sUF3jgNaRfob0kAyXAxf99n09+M5fI8VlFC0OEpmKGHUXez9EFMAqFeZ85eMePvXOX6EmloCPUY3LcX0tGefFQn402tSZCMdIzXwsjTYe5Ku4bGsH+etXRViX+teZmct7BBQ="

services:
 - memcached
 - redis-server

before_script:
 - if [[ "$SKIP_MEMCACHE" != "1" ]]; then phpenv config-add .travis.php.memcache.ini ; fi
 - phpenv config-add .travis.php.memcached.ini
 - phpenv config-add .travis.php.redis.ini
 - composer self-update || true
 - if [[ "$SKIP_MEMCACHE" == "1" ]]; then composer config platform.ext-memcache 0.0.1 ; fi
 - composer install
 - vendor/bin/phpunit --version

script: vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
